### ISSUE TITLE
Donot find the Vuex/Stylus/Axios dependencies in package.json

### ISSUE THREAD

**Issue by x-bingxin** [SimonZhangITer/VueDemo_Sell_Eleme#1]
Hi Simon,

This demo is amazing, while I was trying to run and build in my local, got several issues, couldn't find the modules mentioned in title line. Thanks for your sharing, cheers.

**Comment by SimonZhangITer** [comment]
Thanks for your praise and i’m sorry for this issue

Maybe i was forgot to update the package.json and i will update it as soon as i can.
In order to solve the problem faster,you can use npm to install Vuex/Stylus/Axios.
for example:
“npm install vuex —save”

sorry for that again

**Comment by SimonZhangITer** [comment]
i have fixed this issue,just pull the code again

thanks

**Comment by Jimmy2Angel** [comment]
help~help~
