### ISSUE TITLE
弱弱的问一句npm run build是什么意思

### ISSUE THREAD

**Issue by WangYuLue** [SimonZhangITer/VueDemo_Sell_Eleme#10]
不太懂

**Comment by SimonZhangITer** [comment]
@WangYuLue 
这个是用webpack封装的项目打包命令，在命令行运行后会生成dist文件夹，这个就是打包后的文件夹

**Comment by WangYuLue** [comment]
看到dist文件夹了，这个文件夹是不是在实际部署的时候用的？

**Comment by SimonZhangITer** [comment]
@WangYuLue 
是的，只需要把这个文件夹部署到服务器就可以了

**Comment by WangYuLue** [comment]
谢谢大神，尝试了在服务器上部署了，成功了。
不过还有一个小疑惑，为什么在文件夹里直接打开就没有用？

**Comment by SimonZhangITer** [comment]
@WangYuLue 
这里面是有路由的 需要服务器的解析
