### ISSUE TITLE
请问是下this.$root.eventHub.$emit('cart.add', event.target) 中的cart.add在哪里有定义

### ISSUE THREAD

**Issue by yourenA** [SimonZhangITer/VueDemo_Sell_Eleme#14]
刚接触vue没多久，请问一下，如题

**Comment by yourenA** [comment]
还有请问一下Vue.filter('time',fun)在 filter/time.js 中注册了time过滤器，请问在哪里有引用到这个注册文件

**Comment by SimonZhangITer** [comment]
'cart.add'是广播，在shopCart组件里面接收。

time过滤器在foodDetail里面有用到
