### ISSUE TITLE
请问怎么把dist文件放在gh-pages目录下的

### ISSUE THREAD

**Issue by 793405936** [SimonZhangITer/VueDemo_Sell_Eleme#20]
请问怎么把dist文件放在gh-pages目录下的

**Comment by SimonZhangITer** [comment]
创建dist分支，然后把打包后的dist文件全部复制到当前分支下

**Comment by 793405936** [comment]
好的，谢谢




------------------ 原始邮件 ------------------
发件人: "Simon Zhang";<notifications@github.com>;
发送时间: 2017年5月27日(星期六) 上午9:20
收件人: "SimonZhangITer/VueDemo_Sell_Eleme"<VueDemo_Sell_Eleme@noreply.github.com>; 
抄送: "丽"<793405936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SimonZhangITer/VueDemo_Sell_Eleme] 请问怎么把dist文件放在gh-pages目录下的 (#20)




创建dist分支，然后把打包后的dist文件全部复制到当前分支下
