### ISSUE TITLE
兄弟组件通讯问题

### ISSUE THREAD

**Issue by z775356703** [SimonZhangITer/VueDemo_Sell_Eleme#21]
官方文档说 创建一个空实例  var  xxx=new vue();      问题1.  兄弟2 控制台没有打印出 传递的值。  问题2.这个空实例在哪里创建！ 求大佬指点！

                                      兄弟A     xxx.$emit('xxxxx', event.target);
                                      
                                      兄弟B    methods: {
                                                             drop(el)  {
                                                                     console.log(el);
                                                                    }
                                                           },
                                                 created()  {
                                                                    xxx.$on('cart.add',this.drop);
     
                                                                    }

**Comment by SimonZhangITer** [comment]
可以把广播挂载到根节点或者两个兄弟元素的父元素上。这样两边都可以接收到信息。比如：
```
this.$root.eventHub.$emit('xxx',xxx)
```
在main.js中:
```
data() {
  eventHub : new Vue()
}
```

**Comment by z775356703** [comment]
我试试看，谢谢哈~
