### ISSUE TITLE
关于打包上传github的问题

### ISSUE THREAD

**Issue by jiaolongshenme** [SimonZhangITer/VueDemo_Sell_Eleme#22]
![image](https://cloud.githubusercontent.com/assets/22339560/26673552/de1a8fc6-46ef-11e7-8afa-302615e9cc56.png)
我打包上传后能得到页面，但是获取不到数据这是什么问题
求帮忙解答谢谢

**Comment by jiaolongshenme** [comment]
![image](https://cloud.githubusercontent.com/assets/22339560/26677837/230259d8-4700-11e7-851c-525a3c9af6a7.png)

为什么你的xhr获取的事data.json我得是seller，goods，rating

**Comment by SimonZhangITer** [comment]
你是从慕课网上面看的吧，那个是从本地node起了一个服务器模拟了接口请求，打包之后就是正式环境不生效了。所以这里最后改成请求本地json，把json文件放在static文件夹下面就可以了

**Comment by Skura23** [comment]
我也遇到这个问题, 请问你现在解决了么

**Comment by Skura23** [comment]
这个我最后解决了,我是这样做的:
1, 先把vue-resource替换成了axios
2, 把获取数据语句换成这样: axios.get('static/data.json')的形式, 共有三处, 参考作者源码
3, 重新打包
参考issue: #11
