### ISSUE TITLE
获取不了模拟的data.json数据

### ISSUE THREAD

**Issue by chanliyshun** [SimonZhangITer/VueDemo_Sell_Eleme#24]
![image](https://user-images.githubusercontent.com/23210819/27782593-b2b42700-6005-11e7-90de-0b89cf8bf49e.png)
![image](https://user-images.githubusercontent.com/23210819/27782803-8edda8aa-6006-11e7-82f1-0f7f04f12929.png)

编译后上传了dist文件的内容，只能渲染出静态页面获取不了data.json的数据，请问这是为什么呢？

**Comment by SimonZhangITer** [comment]
你现在应该是在webpack里面写了node来模拟接口吧，可以换成请求json的方式，就是直接请求在static里面的json文件进行渲染。另外还有一个需要注意的问题是：所有的相对路径要改成'./xxx'这样的格式

**Comment by chanliyshun** [comment]
还是不懂。是指修改dev-server.js里面的配置吗？还是需要用Json-Server？
![image](https://user-images.githubusercontent.com/23210819/27791500-ee70bf8e-6027-11e7-8133-7c49b1652325.png)
