### ISSUE TITLE
数据不同步的问题

### ISSUE THREAD

**Issue by Fish-Fan** [SimonZhangITer/VueDemo_Sell_Eleme#25]
GoodsDetail组件内的评价不能根据Food进行刷新，另外评价的数量也不对

**Comment by Fish-Fan** [comment]
![2017-07-08 10 35 57](https://user-images.githubusercontent.com/16412949/27981971-566134e4-63c9-11e7-879e-3aaf359cb3e9.png)
将data中的count放在computed重新计算即可

**Comment by SimonZhangITer** [comment]
这点我之前还没注意到，非常感谢你的建议^_^
