### ISSUE TITLE
请问使用better-scroll后，pc浏览时，点击事件被默认阻止掉了是怎么回事？

### ISSUE THREAD

**Issue by LysaFeng** [SimonZhangITer/VueDemo_Sell_Eleme#29]
按照慕课网教程上说的，当切换到pc端时，只会出现点击一次，触发两次事件的情况。但是我切换到pc后浏览，点击事件就失效了。

麻烦大神看到之后能回复一下我。感谢

**Comment by zhang19961234** [comment]
new BScroll(menuWrapper,{
     click:true
});
如上，加一个click:true就可以了
