### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by sunhaoxiang** [SimonZhangITer/VueDemo_Sell_Eleme#6]
进入详情页点击加入购物车，然后返回，换一个详情页再点击加入购物车，之后在详情页点加号每次加的数量就不是1了

**Comment by SimonZhangITer** [comment]
谢谢你的建议，你不说我还真没发现。
我马上会修改并更新代码，抱歉

**Comment by SimonZhangITer** [comment]
已经修复并提交代码。

原因是详情页的scroll多次初始化，改成单例，然后refresh即可
