### ISSUE TITLE
想请问下这个demo还有哪些功能在计划加进来的吗？

### ISSUE THREAD

**Issue by xeoshow** [SimonZhangITer/VueDemo_Sell_Eleme#8]
演示效果不错，学习了。想请问下这个demo还有哪些功能在计划加进来的吗？

**Comment by SimonZhangITer** [comment]
@xeoshow 暂时没有新的功能，目前可能会把时间放在我的另一个数据可视化项目的新版本上   [https://github.com/SimonZhangITer/DataVisualization](https://github.com/SimonZhangITer/DataVisualization)

**Comment by urumchi** [comment]
@SimonZhangITer 大牛，我能不能提两点新功能：
1. header里的公告，能不能做成滚动的，比如一个商家有5条公告，轮询显示或者滚动显示；
2. 能不能完善一下购物车，点击结算后的页面。

**Comment by SimonZhangITer** [comment]
@si-tech 不错的建议。不过暂时可能没有时间，等有空我做一下，到时候通知你。感谢支持

**Comment by xeoshow** [comment]
有个功能挺值得做进来，方便大家学习vuejs的深入功能，就是菜品实时搜索。比如右上方加个搜索输入框，输入文字当前右侧主区域的菜品列表显示实时结果。
这个功能出来我可以Donate几杯咖啡 :D


2017-02-21 11:18 GMT+08:00 Simon Zhang <notifications@github.com>:

**Comment by xeoshow** [comment]
qtool，我们都多Donate一点，让大牛可以持续完善下哈，慢慢远远超过慕课网的老版本例子。。。

在 2017年2月25日 上午8:54，xeoshow <xeoshow@gmail.com>写道：

**Comment by SimonZhangITer** [comment]
@xeoshow 感谢支持^_^
