### ISSUE TITLE
😊

### ISSUE THREAD

**Issue by bailicangdu** [SimonZhangITer/VueDemo_Sell_Eleme#9]

**Comment by SimonZhangITer** [comment]
@bailicangdu 
其实有很多人第一眼看到都是这么认为的，但是事实是慕课网上面的教程是vue1.0并且没有使用vuex、axios等插件，这个项目是我的自己使用vue2.0+vuex+vue-router+axios写的项目。

谢谢！

**Comment by xeoshow** [comment]
支持！

**Comment by weiyaoxiang** [comment]
厉害了
